"""Generate the release results tables from the immutable v3 run id (J07).

Every number in the README results block and in docs/RESULTS.md is PARSED from artifacts that the v3
manifest (`gate12_5-dataset-v3.json`) content-binds by SHA-256 — never hand-typed. Regenerate with
`make readme-tables`. If the manifest or a bound artifact is missing, this refuses (no immutable run
id -> no published number).

Writes:
  * docs/RESULTS.md         — full generated results doc (anchor + detection + localization tables).
  * README.md               - replaces the block between the GENERATED markers with a headline.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MANIFEST = REPO / "artifacts" / "manifests" / "gate12_5-dataset-v3.json"
REPORTS = REPO / "evals" / "reports"
LOCALIZATION = REPORTS / "localization-v3.txt"
DETECTION = REPORTS / "gate12_5-detection-v3.txt"

BEGIN = "<!-- BEGIN GENERATED: results (make readme-tables) -->"
END = "<!-- END GENERATED: results -->"


def _refuse(msg: str) -> int:
    print(f"[REFUSED] {msg}")
    return 1


def parse_localization_auroc(text: str) -> list[tuple[str, list[str]]]:
    """Parse 'AUROC (test), per class:' -> [(class, [RULE,MLP.v1,MLP.v2,GNN.v1,GNN.v2])]."""
    rows: list[tuple[str, list[str]]] = []
    lines = text.splitlines()
    i = next((k for k, ln in enumerate(lines) if ln.startswith("AUROC (test), per class:")), None)
    if i is None:
        return rows
    for ln in lines[i + 2 :]:  # skip the header row
        if not ln.strip():
            break
        parts = ln.split()
        if len(parts) >= 6 and re.match(r"^[a-z_]+$", parts[0]):
            rows.append((parts[0], parts[1:6]))
    return rows


def parse_gray_top1(text: str) -> list[tuple[str, list[str]]]:
    """Parse 'gray exact-link TOP-1 (test)' -> [(class, [RULE,MLP.v1,MLP.v2,GNN.v1,GNN.v2])]."""
    rows: list[tuple[str, list[str]]] = []
    lines = text.splitlines()
    i = next((k for k, ln in enumerate(lines) if ln.startswith("gray exact-link TOP-1")), None)
    if i is None:
        return rows
    for ln in lines[i + 2 :]:
        if not ln.strip():
            break
        parts = ln.split()
        if len(parts) >= 6 and re.match(r"^[a-z_]+$", parts[0]):
            rows.append((parts[0], parts[1:6]))
    return rows


def parse_detection(text: str) -> dict:  # type: ignore[type-arg]
    """Parse the [test] summary line + per-class recall from the detection artifact."""
    out: dict = {"test": None, "per_class": []}  # type: ignore[type-arg]
    for ln in text.splitlines():
        if ln.startswith("[test]"):
            rec = re.search(r"recall=([\d.]+)", ln)
            f1 = re.search(r"F1=([\d.]+)", ln)
            fp = re.search(r"FP/healthy=([\d.]+)", ln)
            det = re.search(r"\[(\d+)/(\d+) faults", ln)
            out["test"] = {
                "recall": rec.group(1) if rec else "?",
                "f1": f1.group(1) if f1 else "?",
                "fp": fp.group(1) if fp else "?",
                "detected": f"{det.group(1)}/{det.group(2)}" if det else "?",
            }
    m = re.search(r"per-class recall \(all splits\):\n(.*?)(?:\n\n|\Z)", text, re.S)
    if m:
        for ln in m.group(1).splitlines():
            p = ln.split()
            if len(p) >= 3 and "/" in p[1]:
                out["per_class"].append((p[0], p[1], p[-1].strip("()")))
    return out


def md_table(header: list[str], rows: list[tuple[str, list[str]]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    for name, cells in rows:
        out.append("| " + " | ".join([f"`{name}`", *cells]) + " |")
    return "\n".join(out)


def build_results_doc(m: dict, loc_txt: str, det_txt: str) -> str:  # type: ignore[type-arg]
    auroc = parse_localization_auroc(loc_txt)
    top1 = parse_gray_top1(loc_txt)
    det = parse_detection(det_txt)
    hdr = ["class", "RULE", "MLP.v1", "MLP.v2", "GNN.v1", "GNN.v2"]
    anchor = (
        f"- **immutable run id (manifest hash):** `{m['manifest_hash']}`\n"
        f"- **source run:** `{', '.join(m['source_run_ids'])}` (under traffic load, fabric-wide)\n"
        f"- **code revision:** `{m['code_revision']}`\n"
        f"- **split:** {m['split_protocol']} (`{m['split_manifest_hash'][:12]}`)\n"
    )
    dt = det["test"] or {}
    det_line = (
        f"detection (test, classical ensemble): recall **{dt.get('recall', '?')}** "
        f"({dt.get('detected', '?')} faults), F1 {dt.get('f1', '?')}, "
        f"FP/healthy {dt.get('fp', '?')}."
    )
    det_pc = "\n".join(f"| `{c}` | {d} | {tag} |" for c, d, tag in det["per_class"])
    return f"""# ClosCall — Results (generated)

> Generated by `make readme-tables` from the immutable v3 run id. Every number below is parsed from
> artifacts the manifest content-binds by SHA-256 — none are hand-typed. Do not edit by hand.

## Immutable run anchor
{anchor}

## Headline: detection is blind to gray faults; learned localization recovers them
{det_line}

The classical single-interface detector sees the **blunt** faults and is **blind to the gray**
faults (rate_limited, impaired) even under load. Localizing the faulted link among 8 candidates, the
oper-state rule is at chance on gray faults while learned MLP/GNN models recover them.

## Localization — AUROC (test), per fault class
{md_table(hdr, auroc)}

## Localization — gray exact-link top-1 (test), the honest weak spot
{md_table(hdr, top1)}

## Detection — per-class recall (all splits)
| class | detected/total | kind |
|---|---|---|
{det_pc}

*Full studies + CIs: `evals/reports/gate12_5-evaluation.md` (regenerate with `make reports-v3`).*
"""


def readme_block(m: dict, loc_txt: str, det_txt: str) -> str:  # type: ignore[type-arg]
    auroc = {c: cells for c, cells in parse_localization_auroc(loc_txt)}
    det = parse_detection(det_txt)
    dt = det["test"] or {}

    def gray(c: str) -> str:
        cells = auroc.get(c, ["?"] * 5)
        return f"rule {cells[0]} -> MLP {cells[2]} / GNN {cells[4]}"  # v2 columns

    anchor_id = m["manifest_hash"][:16]
    runs = ", ".join(m["source_run_ids"])
    code = m["code_revision"][:12]
    det_cell = (
        f"recall **{dt.get('recall', '?')}** ({dt.get('detected', '?')} faults) - blunt only; "
        "gray = 0 (structural blind spot, even under load)"
    )
    det_row = f"| Detection (test, classical ensemble) | {det_cell} |"

    return f"""{BEGIN}
## Results (v3 under-load anchor)

*Generated from immutable run id `{anchor_id}...` (`{runs}`, code `{code}`). Regenerate:
`make readme-tables`. Full tables: [`docs/RESULTS.md`](docs/RESULTS.md).*

**Thesis, on real under-load data:** classical single-interface detection is blind to *gray* faults;
relational/temporal learned *localization* recovers them.

| study | result |
|---|---|
{det_row}
| Localization AUROC, `rate_limited_uplink` | {gray("rate_limited_uplink")} |
| Localization AUROC, `impaired_link` | {gray("impaired_link")} |
| Localization AUROC, blunt faults | rule ~0.92 -> learned ~0.94-0.996 |

Gray-fault localization is recovered from throughput instability (temporal) + cross-link comparison
- structure a single-interface detector cannot use. Honest limits (gray top-1, healthy control at
chance) are in [`docs/RESULTS.md`](docs/RESULTS.md).
{END}"""


def main() -> int:
    if not MANIFEST.exists():
        return _refuse("no v3 manifest — cannot generate results without an immutable run id")
    if not LOCALIZATION.exists() or not DETECTION.exists():
        return _refuse("missing a bound study artifact (localization-v3 / detection-v3)")
    m = json.loads(MANIFEST.read_text())
    loc_txt = LOCALIZATION.read_text()
    det_txt = DETECTION.read_text()

    results = REPO / "docs" / "RESULTS.md"
    results.write_text(build_results_doc(m, loc_txt, det_txt))
    print(f"wrote {results.relative_to(REPO)}")

    readme = REPO / "README.md"
    text = readme.read_text()
    block = readme_block(m, loc_txt, det_txt)
    if BEGIN in text and END in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        # insert after the first heading line
        lines = text.splitlines(keepends=True)
        insert_at = 2 if len(lines) >= 2 else len(lines)
        text = "".join(lines[:insert_at]) + "\n" + block + "\n\n" + "".join(lines[insert_at:])
    readme.write_text(text)
    print(f"updated {readme.relative_to(REPO)} (generated results block)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
